services:
  nginx:
    image: ilia1234559/nginx:task18
    restart: always
    depends_on:
      - apache
    ports:
      - 80:80
      - 443:443
    networks:
      - mynet

  apache:
    image: ilia1234559/apache2-server:task18
    restart: always
    ports:
      - 8080:8080
    networks:
      - mynet

networks:
  mynet:
    driver: bridge


